### ISSUE TITLE
More Balance Suggestions

### ISSUE THREAD

**Issue by ConqAra** [William758/ZetItemTweaks#1]
Nerfs:

Maybe Add a slight Polylute nerf on it's damage (like by 5%), I feel like Ukulele's void counterpart is just stronger overall...?

reduce Runald & Kjaro Bands stacking damage (they stack like crazy with how much more damage you're getting from them when you start getting more than 3). Also indirectly makes singularity band a more contested pick.

reduce ATG stacking damage, it stacks extremely well and can get so op after 3 or 4.

Buffs:

Planula should be stronger for when it's obtained, it really is underwhelming and deserves either a rework or a strong buff. You can only obtain it on stage 5 or later unless you're using certain artifacts.

Happiest Mask, might need a rework or a buff, it's a bit underwhelming for what it does.

Lepton daisy maybe?

Interstellar desk plant can be a joke at some points, very good early on but later on it feels lackluster. Maybe the duration can be changed to be a tad longer, or maybe even stackable?

**Comment by William758** [comment]
I agree on nerfing the damage stacking of band and rockets. Polylute can probably be brought down to +2 strikes per stack instead of +3 to match ukuleles stacking. I'm not really sure how to buff the other items, but for now I can at least add configs for their values.

**Comment by ConqAra** [comment]
👍 sounds good

**Comment by William758** [comment]
Just uploaded a version with the item nerfs.

**Comment by ConqAra** [comment]
forgot to close this lol
