### ISSUE TITLE
Aegis rebalance does not work

### ISSUE THREAD

**Issue by LordVGames** [William758/ZetItemTweaks#4]
The description is changed, but the effect is not there. No armor is gained when you have the item. I've also tried force-enabling it to no avail. I looked in the log for any errors related to it, but couldn't find anything.
Aegis's setup:
```
[Info   :ZetItemTweaks] Aegis :: Proceed with LateSetup.
[Debug  :RoR2BepInExPack] Hook added by assembly: ZetItemTweaks.dll for: RoR2.HealthComponent.Heal
[Debug  :RoR2BepInExPack] Hook added by assembly:  for: RoR2.HealthComponent.Heal
```
This is also how many items were modified:
```
[Info   :ZetItemTweaks] Setup Complete!
[Info   :ZetItemTweaks] Created [350] config entries.
[Info   :ZetItemTweaks] Modified [1] buffDefs.
[Info   :ZetItemTweaks] Modified [2] itemDefs.
[Info   :ZetItemTweaks] Tweaked [44] items.
```

**Comment by William758** [comment]
Can I get the full log to see if there are any errors? The code for item stats is run earlier so it wouldn't show up near Aegis' setup.

**Comment by LordVGames** [comment]
Sure. I only went to the main menu then quit for this log, though.
[LogOutput.log](https://github.com/William758/ZetItemTweaks/files/13848661/LogOutput.log)

Here's the mod list I used as well. I noticed the issue initially in a much larger modpack, but it's still broken even with this smaller set of mods.
<details>
<summary>Mod list</summary>

```
RiskofThunder-R2API_SceneAsset-1.1.1  
RiskofThunder-R2API_Items-1.0.3  
RiskofThunder-R2API_Prefab-1.0.3
RiskofThunder-R2API_TempVisualEffect-1.0.2
RiskofThunder-R2API_Director-2.1.0
RiskofThunder-R2API_CommandHelper-1.0.1
RiskofThunder-R2API_Dot-1.0.1
RiskofThunder-R2API_LobbyConfig-1.0.1
RiskofThunder-R2API_Difficulty-1.1.2
RiskofThunder-BepInEx_GUI-3.0.2
RiskofThunder-FixPluginTypesSerialization-1.0.3
RiskofThunder-RoR2BepInExPack-1.10.0
bbepis-BepInExPack-5.4.2113
RiskofThunder-HookGenPatcher-1.2.3
RiskofThunder-R2API_Core-5.0.11
RiskofThunder-R2API_Skins-1.1.0
RiskofThunder-R2API_Addressables-1.0.3
RiskofThunder-R2API_Elites-1.0.3
RiskofThunder-R2API_Loadout-1.0.2
RiskofThunder-R2API_Sound-1.0.2
RiskofThunder-R2API_Unlockable-1.0.2
RiskofThunder-R2API_ArtifactCode-1.0.1
RiskofThunder-R2API_Deployable-1.0.1
RiskofThunder-R2API_Language-1.0.1
RiskofThunder-R2API_Orb-1.0.1
RiskofThunder-R2API_DamageType-1.0.4
RiskofThunder-R2API_RecalculateStats-1.3.0
RiskofThunder-R2API_Networking-1.0.2
RiskofThunder-R2API_ContentManagement-1.0.3
tristanmcpherson-R2API-5.0.5
Rune580-Risk_Of_Options-2.7.1
Bubbet-ZioConfigFile-1.0.1
Bubbet-ZioRiskOfOptions-1.0.0
Lodington-Aerolt-4.0.10
RiskofThunder-R2API_Colors-1.0.1
KingEnderBrine-LobbySkinsFix-1.2.1
Rune580-StopStealingMyMouse-1.2.0
Bubbet-SkipIntro-1.0.0
Groove_Salad-ProperlyPersistentProfilesPatchPlugin-1.0.0
Nuxlar-MultiplayerModTesting-1.0.0
IHarbHD-DebugToolkit-3.11.0
AceOfShades-QuickRestart-1.4.2
prodzpod-RealerCheatUnlocks-1.0.3
KingEnderBrine-ScrollableLobbyUI-1.8.0
XoXFaby-BetterUI-2.8.4
TeamMoonstorm-MoonstormSharedUtils-1.6.3
William758-ZetItemTweaks-1.2.2
```
</details>

**Comment by William758** [comment]
Yeah I'm not seeing any errors in the log. Do any of the other armor items change armor? Can I get that mod list as a mod manager code so I can debug. Also MultiplayerModTesting is for mod developers testing their mods so most likely does not belong on the list.

**Comment by LordVGames** [comment]
I had MultiplayerModTesting left on when I was testing a bug in a different mod, so I've turned it off for now. The profile code is `018ce06a-bdd3-e9ad-4682-ff2273158839`

I did also go and test the other rebalanced items that give armor:
- Normal pearl & irradiant pearl *do not* give armor
- Rose buckler *does* give armor when sprinting

**Comment by William758** [comment]
Alright found out why its not working. Just updated the mod with the fix.

**Comment by LordVGames** [comment]
Checked it out, aegis + the pearls give armor now. Thanks for the quick fix!
